version: '2.1'
services:
  postgresql-db:
    image: postgres:latest
    ports:
     - 15432:5432
    environment:
     - POSTGRES_USER=wedadm
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=weddb
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql:z
     - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql:z
    networks:
     - wedform-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-test@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
     - ./servers.json:/pgadmin4/servers.json:z
    ports:
      - "${PGADMIN_PORT:-15050}:80"
    networks:
      - wedform-network

networks:
  wedform-network:
   name: wedform-network
